// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAFthYPNea3g1v6177iRjPcpTAN448Dl_8',
    appId: '1:1026703359499:web:6a7495c334b405c21e510e',
    messagingSenderId: '1026703359499',
    projectId: 'agriculture-9bbc9',
    authDomain: 'agriculture-9bbc9.firebaseapp.com',
    storageBucket: 'agriculture-9bbc9.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCgsp0zOTL2SkpbYoSb87t6dXkHvrQR94M',
    appId: '1:1026703359499:android:7bcb7430514076101e510e',
    messagingSenderId: '1026703359499',
    projectId: 'agriculture-9bbc9',
    storageBucket: 'agriculture-9bbc9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCKsY-80OVQbSKShBTXhhnwPPRmItX-qVM',
    appId: '1:1026703359499:ios:f10ea7f03740eb011e510e',
    messagingSenderId: '1026703359499',
    projectId: 'agriculture-9bbc9',
    storageBucket: 'agriculture-9bbc9.appspot.com',
    iosClientId: '1026703359499-8r62mu6fo2rggd934hd25schuq5mpd2d.apps.googleusercontent.com',
    iosBundleId: 'com.example.app',
  );
}
