// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDJQE6gOwllQbuyy29rcbRbvGsOlKMxUIo',
    appId: '1:350343354465:web:436e59b390b347579cf220',
    messagingSenderId: '350343354465',
    projectId: 'agriculture-app-d9038',
    authDomain: 'agriculture-app-d9038.firebaseapp.com',
    storageBucket: 'agriculture-app-d9038.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAUYB7gCuT_udDS5_wFoteL-b8s-mFbvpg',
    appId: '1:350343354465:android:d509749634ae3e1b9cf220',
    messagingSenderId: '350343354465',
    projectId: 'agriculture-app-d9038',
    storageBucket: 'agriculture-app-d9038.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDoi8d5hojrvl1UzVtdzhisfJbEwC3vuCA',
    appId: '1:350343354465:ios:be405c99595ec9489cf220',
    messagingSenderId: '350343354465',
    projectId: 'agriculture-app-d9038',
    storageBucket: 'agriculture-app-d9038.appspot.com',
    iosClientId: '350343354465-t7u8tn3a45tm9ule68pbdoqaai6hsedo.apps.googleusercontent.com',
    iosBundleId: 'com.example.app',
  );
}
